title: Betacoronavirus
description: Thoughts, ideas and facts about betacoronaviruses, Covid and surroundings topics such as the immune system and life forms.


theme: null

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true


baseurl: "/coronavirus"
url: "https://forestgrape.github.io"

