title: Betacoronavirus
description: Thoughts, ideas and facts about betacoronaviruses, Covid and surroundings topics such as the immune system and life forms.


theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true


