title: Betacoronavirus
description: Ideas, proposals and some facts about SARS-2, Covid and related topics such as the immune system, viruses and life.


theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true


